/*
enchant.js v0.4.4
Copyright (c) Ubiquitous Entertainment Inc.
Dual licensed under the MIT or GPL Version 3 licenses
http://www.opensource.org/licenses/mit-license.php
http://www.gnu.org/licenses/gpl-3.0.html
*/
"function"!=typeof Object.defineProperty&&(Object.defineProperty=function(f,i,m){"value"in m&&(f[i]=m.value);"get"in m&&f.__defineGetter__(i,m.get);"set"in m&&f.__defineSetter__(i,m.set);return f});"function"!=typeof Object.defineProperties&&(Object.defineProperties=function(f,i){for(var m in i)i.hasOwnProperty(m)&&Object.defineProperty(f,m,i[m]);return f});
"function"!=typeof Object.create&&(Object.create=function(f,i){function m(){}m.prototype=f;var o=new m;i!=null&&Object.defineProperties(o,i);return o});"function"!=typeof Object.getPrototypeOf&&(Object.getPrototypeOf=function(f){return f.__proto__});
var enchant=function(f){if(f!=null){f instanceof Array||(f=Array.prototype.slice.call(arguments));f=f.filter(function(f){return""+f})}(function m(o,q){var c=[],n;for(n in o)if(o.hasOwnProperty(n))if(typeof o[n]=="function")window[n]=o[n];else if(typeof o[n]=="object"&&Object.getPrototypeOf(o[n])==Object.prototype)if(f==null)c.push(n);else{a=f.indexOf(q+n);if(a!=-1){c.push(n);f.splice(a,1)}}var a=0;for(n=c.length;a<n;a++)m(o[c[a]],q+c[a]+".")})(enchant,"");if(f!=null&&f.length)throw Error("Cannot load module: "+
f.join(", "));};
(function(){function f(a){var b=a.match(/\.\w+$/);return b&&b.length>0?b[0].slice(1).toLowerCase():a.indexOf("data:")===0?a.split(/[\/;]/)[1].toLowerCase():null}var i=function(){var a=navigator.userAgent;return a.indexOf("Opera")!=-1?"O":a.indexOf("MSIE")!=-1?"ms":a.indexOf("WebKit")!=-1?"webkit":navigator.product=="Gecko"?"Moz":""}(),m=function(){var a=document.createElement("div");a.setAttribute("ontouchstart","return");return typeof a.ontouchstart=="function"}(),o=function(){if(navigator.userAgent.indexOf("iPhone")!=-1&&
window.devicePixelRatio==2){var a=document.querySelector('meta[name="viewport"]');if(a==null){a=document.createElement("meta");document.head.appendChild(a)}a.setAttribute("content","width=640px");return true}return false}(),q=function(){var a=navigator.userAgent,b=navigator.vendor||"";return location.href.indexOf("http")==0&&a.indexOf("Mobile")==-1&&b.indexOf("Apple")!=-1?true:false}(),c;enchant.Class=function(a,b){return enchant.Class.create(a,b)};enchant.Class.create=function(a,b){if(arguments.length==
0)return enchant.Class.create(Object,b);if(arguments.length==1&&typeof arguments[0]!="function")return enchant.Class.create(Object,arguments[0]);for(var e in b)if(b.hasOwnProperty(e))if(typeof b[e]=="object"&&Object.getPrototypeOf(b[e])==Object.prototype){if(!("enumerable"in b[e]))b[e].enumerable=true}else b[e]={value:b[e],enumerable:true,writable:true};var d=function(){if(this instanceof d)d.prototype.initialize.apply(this,arguments);else return new d};d.prototype=Object.create(a.prototype,b);d.prototype.constructor=
d;if(d.prototype.initialize==null)d.prototype.initialize=function(){a.apply(this,arguments)};return d};enchant.Event=enchant.Class.create({initialize:function(a){this.type=a;this.target=null;this.localY=this.localX=this.y=this.x=0},_initPosition:function(a,b){this.x=this.localX=(a-c._pageX)/c.scale;this.y=this.localY=(b-c._pageY)/c.scale}});enchant.Event.LOAD="load";enchant.Event.PROGRESS="progress";enchant.Event.ENTER_FRAME="enterframe";enchant.Event.EXIT_FRAME="exitframe";enchant.Event.ENTER="enter";
enchant.Event.EXIT="exit";enchant.Event.ADDED="added";enchant.Event.ADDED_TO_SCENE="addedtoscene";enchant.Event.REMOVED="removed";enchant.Event.REMOVED_FROM_SCENE="removedfromscene";enchant.Event.TOUCH_START="touchstart";enchant.Event.TOUCH_MOVE="touchmove";enchant.Event.TOUCH_END="touchend";enchant.Event.RENDER="render";enchant.Event.INPUT_START="inputstart";enchant.Event.INPUT_CHANGE="inputchange";enchant.Event.INPUT_END="inputend";enchant.Event.LEFT_BUTTON_DOWN="leftbuttondown";enchant.Event.LEFT_BUTTON_UP=
"leftbuttonup";enchant.Event.RIGHT_BUTTON_DOWN="rightbuttondown";enchant.Event.RIGHT_BUTTON_UP="rightbuttonup";enchant.Event.UP_BUTTON_DOWN="upbuttondown";enchant.Event.UP_BUTTON_UP="upbuttonup";enchant.Event.DOWN_BUTTON_DOWN="downbuttondown";enchant.Event.DOWN_BUTTON_UP="downbuttonup";enchant.Event.A_BUTTON_DOWN="abuttondown";enchant.Event.A_BUTTON_UP="abuttonup";enchant.Event.B_BUTTON_DOWN="bbuttondown";enchant.Event.B_BUTTON_UP="bbuttonup";enchant.EventTarget=enchant.Class.create({initialize:function(){this._listeners=
{}},addEventListener:function(a,b){var e=this._listeners[a];e==null?this._listeners[a]=[b]:e.indexOf(b)==-1&&e.unshift(b)},removeEventListener:function(a,b){var e=this._listeners[a];if(e!=null){var d=e.indexOf(b);d!=-1&&e.splice(d,1)}},clearEventListener:function(a){a!=null?delete this._listeners[a]:this._listeners={}},dispatchEvent:function(a){a.target=this;a.localX=a.x-this._offsetX;a.localY=a.y-this._offsetY;if(this["on"+a.type]!=null)this["on"+a.type]();var b=this._listeners[a.type];if(b!=null)for(var b=
b.slice(),e=0,d=b.length;e<d;e++)b[e].call(this,a)}});enchant.Game=enchant.Class.create(enchant.EventTarget,{initialize:function(a,b){if(window.document.body===null)throw Error("document.body is null. Please excute 'new Game()' in window.onload.");enchant.EventTarget.call(this);var e=true;if(c){e=false;c.stop()}c=enchant.Game.instance=this;this.width=a||320;this.height=b||320;this.scale=1;var d=document.getElementById("enchant-stage");if(d){var l=window.getComputedStyle(d),a=parseInt(l.width),b=parseInt(l.height);
if(a&&b)this.scale=Math.min(a/this.width,b/this.height);else{d.style.width=this.width+"px";d.style.height=this.height+"px"}for(;d.firstChild;)d.removeChild(d.firstChild);d.style.position="relative";l=d.getBoundingClientRect();this._pageX=Math.round(window.scrollX+l.left);this._pageY=Math.round(window.scrollY+l.top)}else{d=document.createElement("div");d.id="enchant-stage";d.style.width=window.innerWidth+"px";d.style.height=window.innerHeight+"px";d.style.position="absolute";document.body.firstChild?
document.body.insertBefore(d,document.body.firstChild):document.body.appendChild(d);this.scale=Math.min(window.innerWidth/this.width,window.innerHeight/this.height);this._pageY=this._pageX=0}if(!this.scale)this.scale=1;d.style.fontSize="12px";d.style.webkitTextSizeAdjust="none";this._element=d;this.fps=30;this.frame=0;this.ready=null;this.running=false;this.assets={};var g=this._assets=[];(function s(a){a.assets instanceof Array&&[].push.apply(g,a.assets);for(var b in a)a.hasOwnProperty(b)&&typeof a[b]==
"object"&&Object.getPrototypeOf(a[b])==Object.prototype&&s(a[b])})(enchant);this._scenes=[];this.currentScene=null;this.rootScene=new enchant.Scene;this.pushScene(this.rootScene);this.loadingScene=new enchant.Scene;this.loadingScene.backgroundColor="#000";var h=this.width*0.9|0,p=this.width*0.3|0,j=h*0.05|0,d=new enchant.Sprite(h,p);d.x=(this.width-h)/2;d.y=(this.height-p)/2;var k=new enchant.Surface(h,p);k.context.fillStyle="#fff";k.context.fillRect(0,0,h,p);k.context.fillStyle="#000";k.context.fillRect(j,
j,h-j*2,p-j*2);d.image=k;var f=0,i=0;this.addEventListener("progress",function(a){f=a.loaded/a.total});d.addEventListener("enterframe",function(){i=i*0.9;i=i+f*0.1;k.context.fillStyle="#fff";k.context.fillRect(j,0,(h-j*2)*i,p)});this.loadingScene.addChild(d);this._soundID=this._surfaceID=this._mousedownID=0;this._intervalID=null;this.input={};this._keybind={};this.keybind(37,"left");this.keybind(38,"up");this.keybind(39,"right");this.keybind(40,"down");var n=0;["left","right","up","down","a","b"].forEach(function(a){this.addEventListener(a+
"buttondown",function(b){if(!this.input[a]){this.input[a]=true;this.dispatchEvent(new enchant.Event(n++?"inputchange":"inputstart"))}this.currentScene.dispatchEvent(b)});this.addEventListener(a+"buttonup",function(b){if(this.input[a]){this.input[a]=false;this.dispatchEvent(new enchant.Event(--n?"inputchange":"inputend"))}this.currentScene.dispatchEvent(b)})},this);if(e){d=enchant.Game.instance._element;document.addEventListener("keydown",function(a){c.dispatchEvent(new enchant.Event("keydown"));if(37<=
a.keyCode&&a.keyCode<=40||a.keyCode==32){a.preventDefault();a.stopPropagation()}if(c.running)if(a=c._keybind[a.keyCode]){a=new enchant.Event(a+"buttondown");c.dispatchEvent(a)}},true);document.addEventListener("keyup",function(a){if(c.running)if(a=c._keybind[a.keyCode]){a=new enchant.Event(a+"buttonup");c.dispatchEvent(a)}},true);if(m){d.addEventListener("touchstart",function(a){var b=a.target.tagName.toLowerCase();b!=="input"&&b!=="textarea"&&a.preventDefault()},true);d.addEventListener("touchmove",
function(a){var b=a.target.tagName.toLowerCase();if(b!=="input"&&b!=="textarea"){a.preventDefault();c.running||a.stopPropagation()}},true);d.addEventListener("touchend",function(a){var b=a.target.tagName.toLowerCase();if(b!=="input"&&b!=="textarea"){a.preventDefault();c.running||a.stopPropagation()}},true)}else{d.addEventListener("mousedown",function(a){var b=a.target.tagName.toLowerCase();if(b!=="input"&&b!=="textarea"){a.preventDefault();c._mousedownID++;c.running||a.stopPropagation()}},true);d.addEventListener("mousemove",
function(a){var b=a.target.tagName.toLowerCase();if(b!=="input"&&b!=="textarea"){a.preventDefault();c.running||a.stopPropagation()}},true);d.addEventListener("mouseup",function(a){var b=a.target.tagName.toLowerCase();if(b!=="input"&&b!=="textarea"){a.preventDefault();c.running||a.stopPropagation()}},true)}}},preload:function(a){a instanceof Array||(a=Array.prototype.slice.call(arguments));[].push.apply(this._assets,a)},load:function(a,b){b==null&&(b=function(){});var e=f(a);switch(e){case "jpg":case "jpeg":case "gif":case "png":case "bmp":c.assets[a]=
enchant.Surface.load(a);c.assets[a].addEventListener("load",b);break;case "mp3":case "aac":case "m4a":case "wav":case "ogg":c.assets[a]=enchant.Sound.load(a,"audio/"+e);c.assets[a].addEventListener("load",b);break;default:var d=new XMLHttpRequest;d.open("GET",a,true);d.onreadystatechange=function(){if(d.readyState==4){if(d.status!=200&&d.status!=0)throw Error(d.status+": Cannot load an asset: "+a);var e=d.getResponseHeader("Content-Type")||"";if(e.match(/^image/)){c.assets[a]=enchant.Surface.load(a);
c.assets[a].addEventListener("load",b)}else if(e.match(/^audio/)){c.assets[a]=enchant.Sound.load(a,e);c.assets[a].addEventListener("load",b)}else{c.assets[a]=d.responseText;b()}}};d.send(null)}},start:function(){if(this._intervalID)window.clearInterval(this._intervalID);else if(this._assets.length){if(enchant.Sound.enabledInMobileSafari&&!c._touched&&i=="webkit"&&m){var a=new enchant.Scene;a.backgroundColor="#000";var b=Math.round(c.width/10),e=new enchant.Sprite(c.width,b);e.y=(c.height-b)/2;e.image=
new enchant.Surface(c.width,b);e.image.context.fillStyle="#fff";e.image.context.font=b-1+"px bold Helvetica,Arial,sans-serif";var d=e.image.context.measureText("Touch to Start").width;e.image.context.fillText("Touch to Start",(c.width-d)/2,b-1);a.addChild(e);document.addEventListener("touchstart",function(){c._touched=true;c.removeScene(a);c.start()},true);c.pushScene(a);return}var l={},b=this._assets.filter(function(a){return a in l?false:l[a]=true}),g=0,e=0,h=b.length;for(;e<h;e++)this.load(b[e],
function(){var a=new enchant.Event("progress");a.loaded=++g;a.total=h;c.dispatchEvent(a);if(g==h){c.removeScene(c.loadingScene);c.dispatchEvent(new enchant.Event("load"))}});this.pushScene(this.loadingScene)}else this.dispatchEvent(new enchant.Event("load"));this.currentTime=Date.now();this._intervalID=window.setInterval(function(){c._tick()},1E3/this.fps);this.running=true},debug:function(){this._debug=true;this.rootScene.addEventListener("enterframe",function(a){this._actualFps=1/a});this.start()},
actualFps:{get:function(){return this._actualFps||this.fps}},_tick:function(){var a=Date.now(),b=new enchant.Event("enterframe");b.elapsed=a-this.currentTime;this.currentTime=a;for(var a=this.currentScene.childNodes.slice(),e=Array.prototype.push;a.length;){var d=a.pop();d.dispatchEvent(b);d.age++;d.childNodes&&e.apply(a,d.childNodes)}this.currentScene.dispatchEvent(b);this.dispatchEvent(b);this.dispatchEvent(new enchant.Event("exitframe"));this.frame++},stop:function(){if(this._intervalID){window.clearInterval(this._intervalID);
this._intervalID=null}this.running=false},pause:function(){if(this._intervalID){window.clearInterval(this._intervalID);this._intervalID=null}},resume:function(){this.currentTime=Date.now();this._intervalID=window.setInterval(function(){c._tick()},1E3/this.fps);this.running=true},pushScene:function(a){this._element.appendChild(a._element);this.currentScene&&this.currentScene.dispatchEvent(new enchant.Event("exit"));this.currentScene=a;this.currentScene.dispatchEvent(new enchant.Event("enter"));return this._scenes.push(a)},
popScene:function(){if(this.currentScene==this.rootScene)return this.currentScene;this._element.removeChild(this.currentScene._element);this.currentScene.dispatchEvent(new enchant.Event("exit"));this.currentScene=this._scenes[this._scenes.length-2];this.currentScene.dispatchEvent(new enchant.Event("enter"));return this._scenes.pop()},replaceScene:function(a){this.popScene();return this.pushScene(a)},removeScene:function(a){if(this.currentScene==a)return this.popScene();var b=this._scenes.indexOf(a);
if(b!=-1){this._scenes.splice(b,1);this._element.removeChild(a._element);return a}},keybind:function(a,b){this._keybind[a]=b}});enchant.Game.instance=null;enchant.Node=enchant.Class.create(enchant.EventTarget,{initialize:function(){enchant.EventTarget.call(this);this.age=this._offsetY=this._offsetX=this._y=this._x=0;this.scene=this.parentNode=null;this.addEventListener("touchstart",function(a){this.parentNode&&this.parentNode!=this.scene&&this.parentNode.dispatchEvent(a)});this.addEventListener("touchmove",
function(a){this.parentNode&&this.parentNode!=this.scene&&this.parentNode.dispatchEvent(a)});this.addEventListener("touchend",function(a){this.parentNode&&this.parentNode!=this.scene&&this.parentNode.dispatchEvent(a)})},moveTo:function(a,b){this._x=a;this._y=b;this._updateCoordinate()},moveBy:function(a,b){this._x=this._x+a;this._y=this._y+b;this._updateCoordinate()},x:{get:function(){return this._x},set:function(a){this._x=a;this._updateCoordinate()}},y:{get:function(){return this._y},set:function(a){this._y=
a;this._updateCoordinate()}},_updateCoordinate:function(){if(this.parentNode){this._offsetX=this.parentNode._offsetX+this._x;this._offsetY=this.parentNode._offsetY+this._y}else{this._offsetX=this._x;this._offsetY=this._y}},remove:function(){this._listener&&this.clearEventListener();this.parentNode&&this.removeChild(this)}});enchant.Entity=enchant.Class.create(enchant.Node,{initialize:function(){enchant.Node.call(this);this._element=document.createElement("div");this._style=this._element.style;this._style.position=
"absolute";this._height=this._width=0;this._backgroundColor=null;this._opacity=1;this._visible=true;this._buttonMode=null;if(enchant.Game.instance._debug){this._style.border="1px solid blue";this._style.margin="-1px"}this.buttonMode=null;this.buttonPressed=false;this.addEventListener("touchstart",function(){if(this.buttonMode){this.buttonPressed=true;var a=new enchant.Event(this.buttonMode+"buttondown");this.dispatchEvent(a);c.dispatchEvent(a)}});this.addEventListener("touchend",function(){if(this.buttonMode){this.buttonPressed=
false;var a=new enchant.Event(this.buttonMode+"buttonup");this.dispatchEvent(a);c.dispatchEvent(a)}});var a=this,b=function(){a.dispatchEvent(new enchant.Event("render"))};this.addEventListener("addedtoscene",function(){b();c.addEventListener("exitframe",b)});this.addEventListener("removedfromscene",function(){c.removeEventListener("exitframe",b)});this.addEventListener("render",function(){if(this._offsetX!=this._previousOffsetX)this._style.left=this._offsetX+"px";if(this._offsetY!=this._previousOffsetY)this._style.top=
this._offsetY+"px";this._previousOffsetX=this._offsetX;this._previousOffsetY=this._offsetY});a=this;if(m){this._element.addEventListener("touchstart",function(b){for(var d=b.touches,c=0,g=d.length;c<g;c++){b=new enchant.Event("touchstart");b.identifier=d[c].identifier;b._initPosition(d[c].pageX,d[c].pageY);a.dispatchEvent(b)}},false);this._element.addEventListener("touchmove",function(b){for(var d=b.touches,c=0,g=d.length;c<g;c++){b=new enchant.Event("touchmove");b.identifier=d[c].identifier;b._initPosition(d[c].pageX,
d[c].pageY);a.dispatchEvent(b)}},false);this._element.addEventListener("touchend",function(b){for(var d=b.changedTouches,c=0,g=d.length;c<g;c++){b=new enchant.Event("touchend");b.identifier=d[c].identifier;b._initPosition(d[c].pageX,d[c].pageY);a.dispatchEvent(b)}},false)}else{this._element.addEventListener("mousedown",function(b){var d=b.pageX,l=b.pageY,b=new enchant.Event("touchstart");b.identifier=c._mousedownID;b._initPosition(d,l);a.dispatchEvent(b);a._mousedown=true},false);c._element.addEventListener("mousemove",
function(b){if(a._mousedown){var d=b.pageX,l=b.pageY,b=new enchant.Event("touchmove");b.identifier=c._mousedownID;b._initPosition(d,l);a.dispatchEvent(b)}},false);c._element.addEventListener("mouseup",function(b){if(a._mousedown){var d=b.pageX,l=b.pageY,b=new enchant.Event("touchend");b.identifier=c._mousedownID;b._initPosition(d,l);a.dispatchEvent(b);a._mousedown=false}},false)}},id:{get:function(){return this._element.id},set:function(a){this._element.id=a}},className:{get:function(){return this._element.className},
set:function(a){this._element.className=a}},width:{get:function(){return this._width},set:function(a){this._style.width=(this._width=a)+"px"}},height:{get:function(){return this._height},set:function(a){this._style.height=(this._height=a)+"px"}},backgroundColor:{get:function(){return this._backgroundColor},set:function(a){this._element.style.backgroundColor=this._backgroundColor=a}},opacity:{get:function(){return this._opacity},set:function(a){this._style.opacity=this._opacity=a}},visible:{get:function(){return this._visible},
set:function(a){this._style.display=(this._visible=a)?"block":"none"}},touchEnabled:{get:function(){return this._touchEnabled},set:function(a){this._style.pointerEvents=(this._touchEnabled=a)?"all":"none"}},intersect:function(a){return this.x<a.x+a.width&&a.x<this.x+this.width&&this.y<a.y+a.height&&a.y<this.y+this.height},within:function(a,b){b==null&&(b=(this.width+this.height+a.width+a.height)/4);var e;return(e=this.x-a.x+(this.width-a.width)/2)*e+(e=this.y-a.y+(this.height-a.height)/2)*e<b*b}});
enchant.Sprite=enchant.Class.create(enchant.Entity,{initialize:function(a,b){enchant.Entity.call(this);this.width=a;this.height=b;this._scaleY=this._scaleX=1;this._rotation=0;this._dirty=false;this._image=null;this._frame=0;this._frameSequence=[];this._style.overflow="hidden";this.addEventListener("render",function(){if(this._dirty){this._style[i+"Transform"]=["rotate(",this._rotation,"deg)scale(",this._scaleX,",",this._scaleY,")"].join("");this._dirty=false}});this.addEventListener("enterframe",
function(){if(this._frameSequence.length!==0){var a=this._frameSequence.shift();if(a===null)this._frameSequence=[];else{this._setFrame(a);this._frameSequence.push(a)}}});if(enchant.Game.instance._debug){this._style.border="1px solid red";this._style.margin="-1px";this.addEventListener("touchstart",function(){enchant.Game.instance.running||console.log("touchstart",this)})}},image:{get:function(){return this._image},set:function(a){if(a!=this._image){if(this._image!=null)if(this._image.css)this._style.backgroundImage=
"";else if(this._element.firstChild){this._element.removeChild(this._element.firstChild);if(this._dirtyListener){this.removeEventListener("render",this._dirtyListener);this._dirtyListener=null}else this._image._parent=null}if(a!=null)if(a._css)this._style.backgroundImage=a._css;else if(a._parent){var b=document.createElement("canvas"),e=b.getContext("2d");b.width=a.width;b.height=a.height;e.drawImage(a._element,0,0);this._dirtyListener=function(){if(a._dirty){e.drawImage(a._element);a._dirty=false}};
this.addEventListener("render",this._dirtyListener);this._element.appendChild(b)}else{a._parent=this;this._element.appendChild(a._element)}this._image=a;this.frame=this.frame}}},frame:{get:function(){return this._frame},set:function(a){if(a instanceof Array){var b=a.shift();this._setFrame(b);a.push(b);this._frameSequence=a}else{this._setFrame(a);this._frameSequence=[];this._frame=a}}},_setFrame:function(a){if(this._image!=null){this._frame=a;var b=this._image.width/this._width|0;if(this._image._css)this._style.backgroundPosition=
[-(a%b)*this._width,"px ",-(a/b|0)*this._height,"px"].join("");else if(this._element.firstChild){var e=this._element.firstChild.style;e.left=-(a%b)*this._width+"px";e.top=-(a/b|0)*this._height+"px"}}},scale:function(a,b){b==null&&(b=a);this._scaleX=this._scaleX*a;this._scaleY=this._scaleY*b;this._dirty=true},rotate:function(a){this._rotation=this._rotation+a;this._dirty=true},scaleX:{get:function(){return this._scaleX},set:function(a){this._scaleX=a;this._dirty=true}},scaleY:{get:function(){return this._scaleY},
set:function(a){this._scaleY=a;this._dirty=true}},rotation:{get:function(){return this._rotation},set:function(a){this._rotation=a;this._dirty=true}}});enchant.Label=enchant.Class.create(enchant.Entity,{initialize:function(a){enchant.Entity.call(this);this.width=300;this.text=a},text:{get:function(){return this._element.innerHTML},set:function(a){this._element.innerHTML=a}},font:{get:function(){return this._style.font},set:function(a){this._style.font=a}},color:{get:function(){return this._style.color},
set:function(a){this._style.color=a}}});enchant.Map=enchant.Class.create(enchant.Entity,{initialize:function(a,b){enchant.Entity.call(this);var e=document.createElement("canvas");if(o&&c.scale==2){e.width=c.width*2;e.height=c.height*2;this._style.webkitTransformOrigin="0 0";this._style.webkitTransform="scale(0.5)"}else{e.width=c.width;e.height=c.height}this._element.appendChild(e);this._context=e.getContext("2d");this._tileWidth=a||0;this._tileHeight=b||0;this._image=null;this._data=[[[]]];this.touchEnabled=
this._tight=this._dirty=false;this.collisionData=null;this._listeners.render=null;this.addEventListener("render",function(){if(this._dirty||this._previousOffsetX==null){this._dirty=false;this.redraw(0,0,c.width,c.height)}else if(this._offsetX!=this._previousOffsetX||this._offsetY!=this._previousOffsetY)if(this._tight){var a=-this._offsetX,b=-this._offsetY,e=-this._previousOffsetX,h=-this._previousOffsetY,p=a-e+c.width,j=e-a+c.width,k=b-h+c.height,f=h-b+c.height;if(p>this._tileWidth&&j>this._tileWidth&&
k>this._tileHeight&&f>this._tileHeight){var i;if(p<j){i=0;a=e-a;j=p}else{i=a-e;a=0}if(k<f){p=0;b=h-b}else{p=b-h;b=0;k=f}if(c._buffer==null){c._buffer=document.createElement("canvas");c._buffer.width=this._context.canvas.width;c._buffer.height=this._context.canvas.height}f=c._buffer.getContext("2d");if(this._doubledImage){f.clearRect(0,0,j*2,k*2);f.drawImage(this._context.canvas,i*2,p*2,j*2,k*2,0,0,j*2,k*2);f=this._context;f.clearRect(a*2,b*2,j*2,k*2);f.drawImage(c._buffer,0,0,j*2,k*2,a*2,b*2,j*2,
k*2)}else{f.clearRect(0,0,j,k);f.drawImage(this._context.canvas,i,p,j,k,0,0,j,k);f=this._context;f.clearRect(a,b,j,k);f.drawImage(c._buffer,0,0,j,k,a,b,j,k)}a==0?this.redraw(j,0,c.width-j,c.height):this.redraw(0,0,c.width-j,c.height);b==0?this.redraw(0,k,c.width,c.height-k):this.redraw(0,0,c.width,c.height-k)}else this.redraw(0,0,c.width,c.height)}else this.redraw(0,0,c.width,c.height);this._previousOffsetX=this._offsetX;this._previousOffsetY=this._offsetY})},loadData:function(a){this._data=Array.prototype.slice.apply(arguments);
this._dirty=true;this._tight=false;for(var b=0,e=this._data.length;b<e;b++){for(var d=0,a=this._data[b],c=0,g=a.length;c<g;c++)for(var h=0,f=a[c].length;h<f;h++)a[c][h]>=0&&d++;if(d/(a.length*a[0].length)>0.2){this._tight=true;break}}},hitTest:function(a,b){if(a<0||this.width<=a||b<0||this.height<=b)return false;var e=this._image.width,d=this._image.height,c=this._tileWidth||e,g=this._tileHeight||d,a=a/c|0,b=b/g|0;if(this.collisionData!=null)return this.collisionData[b]&&!!this.collisionData[b][a];
for(var h=0,f=this._data.length;h<f;h++){var j=this._data[h],k;if(j[b]!=null&&(k=j[b][a])!=null&&0<=k&&k<(e/c|0)*(d/g|0))return true}return false},image:{get:function(){return this._image},set:function(a){this._image=a;if(o&&c.scale==2){for(var b=new enchant.Surface(a.width*2,a.height*2),e=this._tileWidth||a.width,d=this._tileHeight||a.height,l=a.width/e|0,g=a.height/d|0,h=0;h<g;h++)for(var f=0;f<l;f++)b.draw(a,f*e,h*d,e,d,f*e*2,h*d*2,e*2,d*2);this._doubledImage=b}this._dirty=true}},tileWidth:{get:function(){return this._tileWidth},
set:function(a){this._tileWidth=a;this._dirty=true}},tileHeight:{get:function(){return this._tileHeight},set:function(a){this._tileHeight=a;this._dirty=true}},width:{get:function(){return this._tileWidth*this._data[0][0].length}},height:{get:function(){return this._tileHeight*this._data[0].length}},redraw:function(a,b,e,d){if(this._image!=null){var c,g,f,i,j;if(this._doubledImage){c=this._doubledImage;g=this._tileWidth*2;f=this._tileHeight*2;i=-this._offsetX*2;j=-this._offsetY*2;a=a*2;b=b*2;e=e*2;
d=d*2}else{c=this._image;g=this._tileWidth;f=this._tileHeight;i=-this._offsetX;j=-this._offsetY}var k=c.width/g|0,m=c.height/f|0,n=Math.max((a+i)/g|0,0),o=Math.max((b+j)/f|0,0),q=Math.ceil((a+i+e)/g),s=Math.ceil((b+j+d)/f);c=c._element;var u=this._context;u.clearRect(a,b,e,d);e=0;for(d=this._data.length;e<d;e++)for(var t=this._data[e],v=Math.min(q,t[0].length),w=Math.min(s,t.length),b=o;b<w;b++)for(a=n;a<v;a++){var r=t[b][a];0<=r&&r<k*m&&u.drawImage(c,r%k*g,(r/k|0)*f,g,f,a*g-i,b*f-j,g,f)}}}});enchant.Group=
enchant.Class.create(enchant.Node,{initialize:function(){enchant.Node.call(this);this.childNodes=[];this._y=this._x=0},addChild:function(a){this.childNodes.push(a);a.parentNode=this;a.dispatchEvent(new enchant.Event("added"));if(this.scene){var b=new enchant.Event("addedtoscene");a.scene=this.scene;a.dispatchEvent(b);a._updateCoordinate();var e=document.createDocumentFragment(),d,c=Array.prototype.push;if(a._element)e.appendChild(a._element);else if(a.childNodes)for(d=a.childNodes.slice().reverse();d.length;){a=
d.pop();a.scene=this.scene;a.dispatchEvent(b);a._element?e.appendChild(a._element):a.childNodes&&c.apply(d,a.childNodes.reverse())}if(e.childNodes.length){for(var f,b=this;b.parentNode;){d=b.parentNode.childNodes;for(d=d.slice(d.indexOf(b)+1).reverse();d.length;){a=d.pop();if(a._element){f=a._element;break}else a.childNodes&&c.apply(d,a.childNodes.slice().reverse())}b=b.parentNode}f?this.scene._element.insertBefore(e,f):this.scene._element.appendChild(e)}}},insertBefore:function(a,b){var e=this.childNodes.indexOf(b);
if(e!=-1){this.childNodes.splice(e,0,a);a.parentNode=this;a.dispatchEvent(new enchant.Event("added"));if(this.scene){var d=new enchant.Event("addedtoscene");a.scene=this.scene;a.dispatchEvent(d);a._updateCoordinate();var c=document.createDocumentFragment(),f,h=Array.prototype.push;if(a._element)c.appendChild(a._element);else if(a.childNodes)for(f=a.childNodes.slice().reverse();f.length;){a=f.pop();a.scene=this.scene;a.dispatchEvent(d);a._element?c.appendChild(a._element):a.childNodes&&h.apply(f,a.childNodes.reverse())}if(c.childNodes.length){for(var i,
d=b;d.parentNode;){if(e!=null){f=this.childNodes.slice(e+1).reverse();e=null}else{f=d.parentNode.childNodes;f=f.slice(f.indexOf(d)+1).reverse()}for(;f.length;){a=f.pop();if(a._element){i=a._element;break}else a.childNodes&&h.apply(f,a.childNodes.slice().reverse())}d=d.parentNode}i?this.scene._element.insertBefore(c,i):this.scene._element.appendChild(c)}}}else this.addChild(a)},removeChild:function(a){var b=this.childNodes.indexOf(a);if(b!=-1){this.childNodes.splice(b,1);a.parentNode=null;a.dispatchEvent(new enchant.Event("removed"));
if(this.scene){b=new enchant.Event("removedfromscene");a.scene=null;a.dispatchEvent(b);if(a._element)this.scene._element.removeChild(a._element);else if(a.childNodes)for(var c=a.childNodes.slice(),d=Array.prototype.push;c.length;){a=c.pop();a.scene=null;a.dispatchEvent(b);a._element?this.scene._element.removeChild(a._element):a.childNodes&&d.apply(c,a.childNodes)}}}},firstChild:{get:function(){return this.childNodes[0]}},lastChild:{get:function(){return this.childNodes[this.childNodes.length-1]}},
_updateCoordinate:function(){if(this.parentNode){this._offsetX=this.parentNode._offsetX+this._x;this._offsetY=this.parentNode._offsetY+this._y}else{this._offsetX=this._x;this._offsetY=this._y}for(var a=0,b=this.childNodes.length;a<b;a++)this.childNodes[a]._updateCoordinate()}});enchant.Scene=enchant.Class.create(enchant.Group,{initialize:function(){enchant.Group.call(this);this._element=document.createElement("div");this._element.style.position="absolute";this._element.style.overflow="hidden";this._element.style.width=
(this.width=c.width)+"px";this._element.style.height=(this.height=c.height)+"px";this._element.style[i+"TransformOrigin"]="0 0";this._element.style[i+"Transform"]="scale("+c.scale+")";this.scene=this;var a=this;if(m){this._element.addEventListener("touchstart",function(b){for(var c=b.touches,d=0,f=c.length;d<f;d++){b=new enchant.Event("touchstart");b.identifier=c[d].identifier;b._initPosition(c[d].pageX,c[d].pageY);a.dispatchEvent(b)}},false);this._element.addEventListener("touchmove",function(b){for(var c=
b.touches,d=0,f=c.length;d<f;d++){b=new enchant.Event("touchmove");b.identifier=c[d].identifier;b._initPosition(c[d].pageX,c[d].pageY);a.dispatchEvent(b)}},false);this._element.addEventListener("touchend",function(b){for(var c=b.changedTouches,d=0,f=c.length;d<f;d++){b=new enchant.Event("touchend");b.identifier=c[d].identifier;b._initPosition(c[d].pageX,c[d].pageY);a.dispatchEvent(b)}},false)}else{this._element.addEventListener("mousedown",function(b){var e=b.pageX,d=b.pageY,b=new enchant.Event("touchstart");
b.identifier=c._mousedownID;b._initPosition(e,d);a.dispatchEvent(b);a._mousedown=true},false);c._element.addEventListener("mousemove",function(b){if(a._mousedown){var e=b.pageX,d=b.pageY,b=new enchant.Event("touchmove");b.identifier=c._mousedownID;b._initPosition(e,d);a.dispatchEvent(b)}},false);c._element.addEventListener("mouseup",function(b){if(a._mousedown){var e=b.pageX,d=b.pageY,b=new enchant.Event("touchend");b.identifier=c._mousedownID;b._initPosition(e,d);a.dispatchEvent(b);a._mousedown=
false}},false)}},backgroundColor:{get:function(){return this._backgroundColor},set:function(a){this._element.style.backgroundColor=this._backgroundColor=a}},_updateCoordinate:function(){this._offsetX=this._x;this._offsetY=this._y;for(var a=0,b=this.childNodes.length;a<b;a++)this.childNodes[a]._updateCoordinate()}});var n=["putImageData","drawImage","drawFocusRing","fill","stroke","clearRect","fillRect","strokeRect","fillText","strokeText"];enchant.Surface=enchant.Class.create(enchant.EventTarget,
{initialize:function(a,b){enchant.EventTarget.call(this);this.width=a;this.height=b;this.context=null;var e="enchant-surface"+c._surfaceID++;if(document.getCSSCanvasContext){this.context=document.getCSSCanvasContext("2d",e,a,b);this._element=this.context.canvas;this._css="-webkit-canvas("+e+")"}else if(document.mozSetImageElement){this._element=document.createElement("canvas");this._element.width=a;this._element.height=b;this._css="-moz-element(#"+e+")";this.context=this._element.getContext("2d");
document.mozSetImageElement(e,this._element)}else{this._element=document.createElement("canvas");this._element.width=a;this._element.height=b;this._element.style.position="absolute";this.context=this._element.getContext("2d");n.forEach(function(a){var b=this.context[a];this.context[a]=function(){b.apply(this,arguments);this._dirty=true}},this)}},getPixel:function(a,b){return this.context.getImageData(a,b,1,1).data},setPixel:function(a,b,c,d,f,g){var h=this.context.createImageData(1,1);h.data[0]=c;
h.data[1]=d;h.data[2]=f;h.data[3]=g;this.context.putImageData(h,a,b)},clear:function(){this.context.clearRect(0,0,this.width,this.height)},draw:function(a){arguments[0]=a=a._element;arguments.length==1?this.context.drawImage(a,0,0):this.context.drawImage.apply(this.context,arguments)},clone:function(){var a=new enchant.Surface(this.width,this.height);a.draw(this);return a},toDataURL:function(){var a=this._element.src;return a?a.slice(0,5)=="data:"?a:this.clone().toDataURL():this._element.toDataURL()}});
enchant.Surface.load=function(a){var b=new Image,c=Object.create(enchant.Surface.prototype,{context:{value:null},_css:{value:"url("+a+")"},_element:{value:b}});enchant.EventTarget.call(c);b.src=a;b.onerror=function(){throw Error("Cannot load an asset: "+b.src);};b.onload=function(){c.width=b.width;c.height=b.height;c.dispatchEvent(new enchant.Event("load"))};return c};enchant.Sound=enchant.Class.create(enchant.EventTarget,{initialize:function(){enchant.EventTarget.call(this);throw Error("Illegal Constructor");
},play:function(){this._element&&this._element.play()},pause:function(){this._element&&this._element.pause()},stop:function(){this.pause();this.currentTime=0},clone:function(){var a;if(this._element instanceof Audio)a=Object.create(enchant.Sound.prototype,{_element:{value:this._element.cloneNode(false)},duration:{value:this.duration}});else{if(q)return this;a=Object.create(enchant.Sound.prototype)}enchant.EventTarget.call(a);return a},currentTime:{get:function(){return this._element?this._element.currentTime:
0},set:function(a){if(this._element)this._element.currentTime=a}},volume:{get:function(){return this._element?this._element.volume:1},set:function(a){if(this._element)this._element.volume=a}}});enchant.Sound.load=function(a,b){if(b==null)var e=f(a),b=e?"audio/"+e:"";var b=b.replace("mp3","mpeg"),d=Object.create(enchant.Sound.prototype);enchant.EventTarget.call(d);var l=new Audio;if(!enchant.Sound.enabledInMobileSafari&&i=="webkit"&&m)window.setTimeout(function(){d.dispatchEvent(new enchant.Event("load"))},
0);else if(!q&&l.canPlayType(b)){l.src=a;l.load();l.autoplay=false;l.onerror=function(){throw Error("Cannot load an asset: "+l.src);};l.addEventListener("canplaythrough",function(){d.duration=l.duration;d.dispatchEvent(new enchant.Event("load"))},false);d._element=l}else if(b=="audio/mpeg"){var g=document.createElement("embed"),e="enchant-audio"+c._soundID++;g.width=g.height=1;g.name=e;g.src="sound.swf?id="+e+"&src="+a;g.allowscriptaccess="always";g.style.position="absolute";g.style.left="-1px";d.addEventListener("load",
function(){Object.defineProperties(g,{currentTime:{get:function(){return g.getCurrentTime()},set:function(a){g.setCurrentTime(a)}},volume:{get:function(){return g.getVolume()},set:function(a){g.setVolume(a)}}});d._element=g;d.duration=g.getDuration()});c._element.appendChild(g);enchant.Sound[e]=d}else window.setTimeout(function(){d.dispatchEvent(new enchant.Event("load"))},0);return d};window.addEventListener("message",function(a){a=JSON.parse(a.data);if(a.type=="event")c.dispatchEvent(new Event(a.value));
else if(a.type=="debug")switch(a.value){case "start":enchant.Game.instance.start();break;case "pause":enchant.Game.instance.pause();break;case "resume":enchant.Game.instance.resume();break;case "tick":enchant.Game.instance._tick()}},false);enchant.Sound.enabledInMobileSafari=false})();
/**
 * nineleap.enchant.js
 * @version 0.3 (2012/02/01)
 * @requires enchant.js v0.4.0 or later
 */
(function(){enchant.nineleap={assets:["start.png","end.png"]};enchant.nineleap.Game=enchant.Class.create(enchant.Game,{initialize:function(a,b){enchant.Game.call(this,a,b);this.addEventListener("load",function(){var a=this;this.startScene=new SplashScene;this.startScene._element.style.zIndex=10;this.startScene.image=this.assets["start.png"];this.startScene.addEventListener("touchend",function(){if(!1==a.started){if(null!=a.onstart)a.onstart();gameStart=a.started=!0}a.currentScene==this&&a.popScene();
this.removeEventListener("touchend",arguments.callee)});this.addEventListener("keydown",function(){if(!1==this.started){if(null!=this.onstart)this.onstart();gameStart=this.started=!0}a.currentScene==a.startScene&&a.popScene();this.removeEventListener("keydown",arguments.callee)});this.pushScene(this.startScene);this.endScene=new SplashScene;this.endScene.image=this.assets["end.png"]});gameStart=this.started=this.scoreQueue=!1},loadImage:function(a,b){null==b&&(b=function(){});this.assets[a]=enchant.Surface.load(a);
this.assets[a].addEventListener("load",b)},start:function(){var a=this;if(this._intervalID)window.clearInterval(this._intervalID);else if(this._assets.length){var b={},d=this._assets.filter(function(a){return a in b?!1:b[a]=!0}),h=void 0!=this._twitterAssets?this._twitterAssets:[],i=void 0!=this._netpriceData?this._netpriceData:[],j=void 0!=this._memoryAssets?this._memoryAssets:[],e=0,f=d.length+h.length+i.length+j.length,c=0,g=d.length;for(;c<g;c++)this.load(d[c],function(){var b=new enchant.Event("progress");
b.loaded=++e;b.total=f;a.dispatchEvent(b);e==f&&(a.removeScene(a.loadingScene),a.dispatchEvent(new enchant.Event("load")))});c=0;for(g=h.length;c<g;c++)this.loadImage(h[c],function(){var b=new enchant.Event("progress");b.loaded=++e;b.total=f;a.dispatchEvent(b);e==f&&(a.removeScene(a.loadingScene),a.dispatchEvent(new enchant.Event("load")))});c=0;for(g=j.length;c<g;c++)this.loadImage(j[c],function(){var b=new enchant.Event("progress");b.loaded=++e;b.total=f;a.dispatchEvent(b);e==f&&(a.removeScene(a.loadingScene),
a.dispatchEvent(new enchant.Event("load")))});c=0;for(g=i.length;c<g;c++)this.loadImage(i[c],function(){var b=new enchant.Event("progress");b.loaded=++e;b.total=f;a.dispatchEvent(b);e==f&&(a.removeScene(a.loadingScene),a.dispatchEvent(new enchant.Event("load")))});this.pushScene(this.loadingScene)}else this.dispatchEvent(new enchant.Event("load"));this.currentTime=Date.now();this._intervalID=window.setInterval(function(){a._tick()},1E3/this.fps);this.running=!0},end:function(a,b,d){void 0!==d&&(this.endScene.image=
d);this.pushScene(this.endScene);"r.jsgames.jp"==location.hostname&&(d=function(){var d=location.pathname.match(/^\/games\/(\d+)/)[1];location.replace(["http://9leap.net/games/",d,"/result?score=",encodeURIComponent(a),"&result=",encodeURIComponent(b)].join(""))},this.endScene.addEventListener("touchend",d),window.setTimeout(d,3E3));enchant.Game.instance.end=function(){}}});enchant.nineleap.SplashScene=enchant.Class.create(enchant.Scene,{image:{get:function(){return this._image},set:function(a){for(this._image=
a;this.firstChild;)this.removeChild(this.firstChild);var b=new Sprite(a.width,a.height);b.image=a;b.x=(this.width-a.width)/2;b.y=(this.height-a.height)/2;this.addChild(b)}}})})();
enchant();
var AW=function(D){var R=function(){0===D.pageYOffset&&D.scrollTo(0,1)};D.onorientationchange=function(){setTimeout(R,100)};D.addEventListener("load",D.onorientationchange,!1);var n,N,r={USER:{UNIT:new Group,CASTLE:new Group,THUMB:new Group},ENEMY:{UNIT:new Group,CASTLE:new Group,THUMB:new Group},MAP_OPTION:{CASTLE_BASE:new Group,THUMB_BASE:new Group},EFFECT:{UNIT:new Group}},E="",y={USER:{},ENEMY:{},no:0},O={USER:[],ENEMY:[]},x={USER:[],ENEMY:[]},K={},H={},L={},M=[],F={USER:[],ENEMY:[]},P=[],G={},
Q,z=function(b,c){var f;void 0===b&&(b={});for(f in c)!0===c.hasOwnProperty(f)&&(b[f]=c[f]);return b},w=function(b){b.layer.addChild(b.sprite);return b.sprite};PUBLIC={};var I=function(){return{TIMELIMIT:function(){return 180},FONT:function(){return"monospace"},UNIT:function(){return{IMAGE:"img/char.gif",CHIP_SIZE:16,FRAME_SIZE:{W:4,H:3},FRAME_LINE:16,FRAME_BLOCK:48,FRAME:{HUMAN:{LANCER:0,WARRIOR:4,KNIGHT:8,ARCHER:12,CLELIC:16,FIRE_MAGE:20,FROST_MAGE:24,WIZARD:28},UNDEAD:{BONE_DOG:32,BONE_WARRIER:36,
BONE_ARCHER:40,SPECTOR:44,BONE_SNAKE:48,GOLEM:52,SHADE:56,ARACHNE:60}},STATUS:{HUMAN:{WARRIOR:{name:"WARRIOR",frame:0,hp:3,speed:2,siege:1,reverse:5,attacked:function(){},dead:function(){}},LANCER:{name:"LANCER",frame:4,hp:4,speed:2,siege:1,reverse:3,attacked:function(){},dead:function(){}},KNIGHT:{name:"KNIGHT",frame:8,hp:5,speed:1.8,siege:1,reverse:8,attacked:function(){},dead:function(){}},ARCHER:{name:"ARCHER",frame:12,hp:2,speed:2.2,siege:1,reverse:4,attacked:function(){},dead:function(){}},
CLELIC:{name:"CLELIC",frame:48,hp:2,speed:1,siege:1,reverse:3,attacked:function(){},dead:function(){}},FIRE_MAGE:{name:"FIRE_MAGE",frame:52,hp:2,speed:1.6,siege:1,reverse:4,attacked:function(){},dead:function(b){b=b.mine;b=new Effect({type:b.type.toUpperCase(),x:b.x,y:b.y,frames:CONST_CASH.EFFECT.FRAME.FIRE});w({layer:r.EFFECT.UNIT,sprite:b})}},FROST_MAGE:{name:"FROST_MAGE",frame:56,hp:2,speed:1.6,siege:1,reverse:4,attacked:function(){},dead:function(b){b=b.mine;b=new Effect({type:b.type.toUpperCase(),
x:b.x,y:b.y,frames:CONST_CASH.EFFECT.FRAME.FROST});w({layer:r.EFFECT.UNIT,sprite:b})}},WIZARD:{name:"WIZARD",frame:60,hp:2,speed:1.6,siege:1,reverse:5,attacked:function(){},dead:function(){}}},UNDEAD:{BONE_DOG:{name:"BONE_DOG",frame:96,hp:1,speed:2.8,siege:1,reverse:1,attacked:function(){},dead:function(){}},BONE_WARRIER:{name:"BONE_WARRIER",frame:100,hp:2,speed:2,siege:1,reverse:1,attacked:function(){},dead:function(){}},BONE_ARCHER:{name:"BONE_ARCHER",frame:104,hp:1,speed:2,siege:1,reverse:1,attacked:function(){},
dead:function(){}},SHADE:{name:"SHADE",frame:108,hp:1,speed:1.8,siege:9,reverse:3,attacked:function(){},dead:function(){}},BONE_SNAKE:{name:"BONE_SNAKE",frame:144,hp:2,speed:2.6,siege:1,reverse:1,attacked:function(){},dead:function(){}},GOLEM:{name:"GOLEM",frame:148,hp:7,speed:1,siege:1,reverse:6,attacked:function(){},dead:function(){}},SPECTOR:{name:"SPECTOR",frame:152,hp:1,speed:1.8,siege:0,reverse:3,attacked:function(){},dead:function(){}},ARACHNE:{name:"ARACHNE",frame:156,hp:3,speed:2,siege:1,
reverse:4,attacked:function(b){b=b.enemy;b.reverse=9;b.speed/=2},dead:function(){}}}},AI:{USER:[{direction:0,prop:"y",sign:-1,order:[1,3,0,2]},{direction:3,prop:"x",sign:-1,order:[0,2,3,1]},{direction:1,prop:"x",sign:1,order:[0,2,1,3]},{direction:2,prop:"y",sign:1,order:[3,1,2,0]}],ENEMY:[{direction:2,prop:"y",sign:1,order:[3,1,2,0]},{direction:3,prop:"x",sign:-1,order:[2,0,3,1]},{direction:1,prop:"x",sign:1,order:[2,0,1,3]},{direction:0,prop:"y",sign:1,order:[3,1,0,2]}]}}},THUMB:function(){return{IMAGE:"img/thumb.png",
CHIP_SIZE:48,FRAME:{HUMAN:{LANCER:0,WARRIOR:1,KNIGHT:2,ARCHER:3,CLELIC:4,FIRE_MAGE:5,FROST_MAGE:6,WIZARD:7},UNDEAD:{BONE_DOG:8,BONE_SNAKE:9,BONE_WARRIER:10,BONE_ARCHER:11,GOLEM:12,ARACHNE:13,SHADE:14,SPECTOR:15}},USER:{POSITION:[[0,384],[48,384],[96,384],[144,384],[0,432],[48,432],[96,432],[144,432]]},ENEMY:{},PROP:{}}},SCORE:function(){return{POSITION:[20,7]}},COUNTDOWN:function(){return{POSITION:[200,7]}},STATUS_VIEWER:function(){return{IMAGE:"img/window_status.png",POSITION:[192,384],BG_SIZE:[128,
96]}},MAP:function(){return{IMAGE:"img/map.png",W:320,H:480,CHIP_SIZE:32}},CASTLE:function(){return{FRAME:[{NORMAL:8,BRAKE:9},{NORMAL:10,BRAKE:11},{NORMAL:12,BRAKE:13},{NORMAL:14,BRAKE:15}],PROP:{frame:0,brake:0,hp:2,mhp:2,unitX:0,unitY:0}}},EFFECT:function(){return{IMAGE:"img/effect.gif",FRAME:{EXPLOSION:{start:0,end:5,rate:3,loop:!1},FIRE:{start:6,end:8,rate:50,loop:!1},FROST:{start:11,end:11,rate:10,loop:!1}}}},SOUND:function(){return{BGM:"sound/bgm.wav",EFFECT:{EXPLOSION:"sound/explosion.wav"}}},
TYPE:function(){return{CASTLE:"CASTLE",THUMB:"THUMB",UNIT:"UNIT",EFFECT:"EFFECT"}},HAVE:function(){return{USER:"USER",ENEMY:"ENEMY"}},POINT:function(){return{UNIT:10,CASTLE:1E3,WIN:5E3,LOSE:-5E3,TIME:100}}}};CONST_CASH=I();CONST_CASH={TIMELIMIT:CONST_CASH.TIMELIMIT(),FONT:CONST_CASH.FONT(),UNIT:CONST_CASH.UNIT(),THUMB:CONST_CASH.THUMB(),SCORE:CONST_CASH.SCORE(),COUNTDOWN:CONST_CASH.COUNTDOWN(),STATUS_VIEWER:CONST_CASH.STATUS_VIEWER(),MAP:CONST_CASH.MAP(),CASTLE:CONST_CASH.CASTLE(),EFFECT:CONST_CASH.EFFECT(),
SOUND:CONST_CASH.SOUND(),TYPE:CONST_CASH.TYPE(),HAVE:CONST_CASH.HAVE(),POINT:CONST_CASH.POINT()};PUBLIC.init=function(b){var c=CONST_CASH.UNIT.IMAGE,f=CONST_CASH.THUMB.IMAGE,d=CONST_CASH.MAP.IMAGE,e=CONST_CASH.EFFECT.IMAGE,g=CONST_CASH.STATUS_VIEWER.IMAGE,a=CONST_CASH.SOUND.EFFECT.EXPLOSION,h=CONST_CASH.MAP.W,j=CONST_CASH.MAP.H,i,l;M=b=b.map;i=0;for(l=b.length;i<l;i++)b[i]=b[i].split("");i={"0":0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,24:0,26:0,27:0,28:0,29:0,30:0,31:0,32:0,33:0,34:0,35:0,36:0,37:0,38:0,39:0,
40:0,41:0,42:0,43:0,44:0,45:0,46:0,47:0,48:0,49:0,50:0,51:0,52:0,25:[0,0,1,0],99:[1,0,0,0],16:[1,0,1,0],17:[0,1,0,1],18:[1,1,1,0],19:[1,0,1,1],20:[0,1,1,0],21:[0,0,1,1],22:[1,1,0,0],23:[1,0,0,1]};var k,p,m,q,o,t=[],b=[].concat([[26,27,28,29,30,31,32,33,34,35],[0,1,1,1,1,1,1,1,1,2]],b,[[5,6,6,6,6,6,6,6,6,7],[36,37,38,39,40,41,42,43,44,45],[46,47,48,49,50,51,52,46,47,48],[49,50,51,52,51,52,46,47,48,49]]);l=0;for(p=b.length;l<p;l++){q=t[l]=[];o=b[l];8===o.length&&(b[l]=o=["3"].concat(o,"4"));k=0;for(m=
o.length;k<m;k++){var B=o,A=k,u=o[k];switch(u){case "\u2502":u=16;break;case "\u2500":u=17;break;case "\u251c":u=18;break;case "\u2524":u=19;break;case "\u250c":u=20;break;case "\u2510":u=21;break;case "\u2514":u=22;break;case "\u2518":u=23;break;case "\u00d7":u=24;break;case "\u25a0":u=25;break;case "\u25a1":u=99}B[A]=u;q[k]=i[o[k]];switch(o[k]){case 25:F.ENEMY.push([k,l]);break;case 99:F.USER.push([k,l]),o[k]=25}}}M=b;P=t;n=new Game(h,j);n.preload(c,f,d,e,g,a);n.onload=Amida;n.start()};RaceSelect=
function(){var b=CONST_CASH.THUMB,c=b.CHIP_SIZE,f=b.FRAME.HUMAN,d=b.FRAME.UNDEAD,e=new Scene,g=n.assets[b.IMAGE],a=n.assets[CONST_CASH.STATUS_VIEWER.IMAGE],h=new Group,j=new Sprite(c,c),i=new Label,l=new Label,k=new Sprite(250,100),p=new Group,c=new Sprite(c,c),m=new Label,q=new Label,o=new Sprite(250,100),t=function(a){var c,f,d,g,e=new Label,h=O.USER,i=CONST_CASH.HAVE.USER,j=b.USER.POSITION,l=b.FRAME;E=a.race;d=a.order;c=0;for(f=d.length;c<f;c++)a=d[c].toUpperCase(),g=j[c],h[c]=new Thumb({mode:i,
name:a,frame:l[E][a],x:g[0],y:g[1]});e.text="\u2462";e.font="150px/1.5 "+CONST_CASH.FONT;e.color="#fff";e.x=90;e.y=100;n.rootScene.addChild(e);L.init();n.popScene();aid=setTimeout(function(){e.text="\u2461";aid=setTimeout(function(){e.text="\u2460";aid=setTimeout(function(){G.vibrate(3);c=0;for(f=d.length;c<f;c++)h[c].init();s.init();J.init();H.init();n.rootScene.removeChild(e)},1E3)},1E3)},1E3)};e.backgroundColor="rgba(0,0,0,0.3)";j.image=c.image=g;k.image=o.image=a;k.frame=o.frame=1;h.addChild(k);
p.addChild(o);h.x=p.x=35;h.y=100;p.y=220;j.frame=f.KNIGHT;c.frame=d.BONE_WARRIER;j.x=c.x=5;j.y=c.y=5;i.font=l.font=m.font=q.font="12px/1.5 "+CONST_CASH.FONT;i.color=l.color=m.color=q.color="#ddd";i.text="<b>HUMAN</b>";m.text="<b>UNDEAD</b>";l.text="\u4f7f\u3044\u3084\u3059\u304f\u3001\u9ad8\u6027\u80fd\u306a\u7a2e\u65cf\u3002\u30d0\u30e9\u30f3\u30b9\u304c\u826f\u304f\u6271\u3044\u3084\u3059\u3044\u3002";q.text="\u6271\u3044\u3065\u3089\u3044\u5c16\u3063\u305f\u6027\u80fd\u3092\u6301\u3064\u30e6\u30cb\u30c3\u30c8\u304c\u591a\u3044\u7a2e\u65cf\u3002<br />\u64cd\u4f5c\u91cf\u306b\u81ea\u4fe1\u304c\u3042\u308b\u4eba\u5411\u3051\u3002";
i.x=m.x=50;i.y=m.y=5;l.width=q.width=200;l.x=q.x=50;l.y=q.y=23;h.addChild(j);h.addChild(i);h.addChild(l);p.addChild(c);p.addChild(m);p.addChild(q);e.addChild(h);e.addChild(p);h.addEventListener(enchant.Event.TOUCH_END,function(){t({race:"HUMAN",order:"LANCER,WARRIOR,KNIGHT,ARCHER,CLELIC,FIRE_MAGE,FROST_MAGE,WIZARD".split(",")})});p.addEventListener(enchant.Event.TOUCH_END,function(){t({race:"UNDEAD",order:"BONE_WARRIER,BONE_ARCHER,BONE_DOG,BONE_SNAKE,GOLEM,ARACHNE,SHADE,SPECTOR".split(",")})});n.pushScene(e)};
Amida=function(){var b=CONST_CASH.MAP.CHIP_SIZE,c=M,f=new Map(b,b),d=n.assets[CONST_CASH.MAP.IMAGE],e=r.USER,g=r.ENEMY,a=CONST_CASH.CASTLE.FRAME,h=CONST_CASH.HAVE.USER,j=r.MAP_OPTION.CASTLE_BASE,i=r.MAP_OPTION.THUMB_BASE,l=r.EFFECT.UNIT,k=n.rootScene,p=CONST_CASH.UNIT.CHIP_SIZE,m=CONST_CASH.SCORE.POSITION,q,o=CONST_CASH.COUNTDOWN.POSITION,t=CONST_CASH.STATUS_VIEWER.POSITION,B,A;N=document.getElementById("enchant-stage");f.image=d;f.loadData(c);f.vibrate=function(a){var b=N.style,a=a+"px";clearInterval(A);
A=setTimeout(function(){b.top=0;b.left=a;A=setTimeout(function(){b.top=a;b.left=0;A=setTimeout(function(){b.top=0;b.left="-"+a;A=setTimeout(function(){b.top=0;b.left=0},30)},30)},30)},30)};f.getSquere=function(a){var c,d,e=Math.floor;f.getSquere=function(a){c=e(a.x/b);d=e(a.y/b);return{x:c,y:d}};return f.getSquere(a)};f.getCollision=function(a){var b=f.getSquere(a),c=P,d=!1,e,g,h;if((c=c[b.y])&&(c=c[b.x]))if(1===c[0]+c[1]+c[2]+c[3])for(e in x){if(!0===x.hasOwnProperty(e)){g=x[e];b=0;for(c=g.length;b<
c;b++)if(h=g[b],!0===a.intersect(h)){d=h;break}}}else d=c;return d};G=f;statusViewer=L=new StatusViwer({mode:h,x:t[0],y:t[1]});c=K=new Score({mode:h,x:m[0],y:m[1]});q=H=new Countdown({x:o[0],y:o[1]});q.update();for(B in F)if(!0===F.hasOwnProperty(B)){h=F[B];o=0;for(d=h.length;o<d;o++)m=new Castle({mode:B,frame:a[o].NORMAL,brake:a[o].BRAKE,x:h[o][0]*b,y:h[o][1]*b}),m.unitX=m.x+p/2,m.unitY=m.y+p/2}k.addChild(f);k.addChild(j);k.addChild(statusViewer);k.addChild(i);k.addChild(g.CASTLE);k.addChild(g.UNIT);
k.addChild(e.UNIT);k.addChild(e.CASTLE);k.addChild(e.THUMB);k.addChild(g.THUMB);k.addChild(l);k.addChild(c.label);k.addChild(q);Q=n.assets[CONST_CASH.SOUND.EFFECT.EXPLOSION];C.init();(function(){var a=!1,b=function(){new Result(a);v.end();J.end();q.stop();n.end();s.end()};v.add(function(){return!0===gameStart?(new RaceSelect,q.setAfter(function(){a=!0;b();return!0}),v.remove("playStart"),!0):!1},"playStart");v.add(function(){var c,d,e,f,g,h;if(!1!==a)return b(),!0;for(c in x)if(!0===x.hasOwnProperty(c)){f=
x[c];e=f.length;for(d=h=0;d<e&&!(g=f[d],0<g.hp);d++)h++;if(h===e){a=c;break}}return!1},"playEnd");v.init()})()};Castle=function(b){var c=CONST_CASH.MAP.CHIP_SIZE,f=n.assets[CONST_CASH.MAP.IMAGE],d=I().CASTLE().PROP,e=b.mode.toUpperCase(),g=CONST_CASH.HAVE,a=new Sprite(c,c),h=r.MAP_OPTION.CASTLE_BASE,j=-1,i,c=new Sprite(c,c);c.image=f;c.frame=24;e===g.USER&&(c.frame=16);c.x=b.x;c.y=b.y;w({layer:h,sprite:c});d.base=c;d=z(d,b);a.image=f;a=z(a,d);a.type=CONST_CASH.TYPE.CASTLE;x[e].push(a);a.focusOn=function(){a.scaleX=
a.scaleY=1.4;a.focus=true};a.focusOff=function(){a.scaleX=a.scaleY=1;a.focus=false};i=function(){if(n.frame%2===0){a.opacity=a.opacity+0.1*j;a.opacity<=0.5?j=1:a.opacity>=1&&(j=-1)}};a.blinkOn=function(){a.addEventListener(enchant.Event.ENTER_FRAME,i)};a.blinkOff=function(){a.removeEventListener(enchant.Event.ENTER_FRAME,i);a.opacity=1};a.damage=function(b){a.hp=a.hp-b.siege;if(a.hp<=0){a.hp=0;a.broke()}else if(a.mhp/2>=a.hp)a.frame=a.brake};a.broke=function(){a.hp=a.opacity=a.base.opacity=0};a.checkBreak=
function(){return a.hp===0?true:false};return w({layer:r[e].CASTLE,sprite:a})};Thumb=function(b){var c=CONST_CASH.THUMB.CHIP_SIZE,f=n.assets[CONST_CASH.THUMB.IMAGE],d=I().THUMB().PROP,e=CONST_CASH.UNIT.STATUS[E][b.name],g=b.mode.toUpperCase(),a=new Sprite(c,c),c=new Sprite(c,c),h,j,i,l,k=enchant.Event,p=L,m=new Label;c.image=f;c.frame=16;c.x=b.x;c.y=b.y;w({layer:r.MAP_OPTION.THUMB_BASE,sprite:c});m.text=Math.ceil(e.reverse);m.font="24px "+CONST_CASH.FONT;m.color="#ccc";m.x=b.x+17;m.y=b.y+7;w({layer:r.MAP_OPTION.THUMB_BASE,
sprite:m});d=z(d,b);a.image=f;a=z(a,d);a.unit={mode:g};a.unit=z(a.unit,e);a.type=CONST_CASH.TYPE.THUMB;i=a.x;l=a.y;a.addEventListener(k.TOUCH_START,function(b){!0===this.canDrag&&(h=b.x-this.x,j=b.y-this.y);p.update(a.unit)});a.addEventListener(k.TOUCH_MOVE,function(a){!0===this.canDrag&&(this.x=a.x-h,this.y=a.y-j)});a.addEventListener(k.TOUCH_END,function(){if(!0===this.canDrag){var a;a=!1;var b=x.USER,c,d,e;d=0;for(e=b.length;d<e;d++)if(c=b[d],!0===this.intersect(c)){a=c;break}!1!==a&&(this.dragStop(),
this.unit.x=a.unitX,this.unit.y=a.unitY,this.lastUnit=new Unit(this.unit),this.lastUnit.thumb=this);this.x=i;this.y=l}});a.dragStart=function(){a.canDrag=!0;a.opacity=1};a.dragStop=function(){a.canDrag=!1;a.opacity=0};a.reverse=function(b){var c=Math.ceil(b.reverse),d=setInterval(function(){c--;m.text=c;0===c&&(m.text="",a.dragStart(),clearInterval(d))},1E3);m.text=c;a.opacity=0.3};O[g].push(a);a.dragStop();a.opacity=0.3;a.init=function(){a.reverse(a.unit)};return w({layer:r[g].THUMB,sprite:a})};
Unit=function(b){var c=CONST_CASH.UNIT.CHIP_SIZE,f=CONST_CASH.MAP.CHIP_SIZE,d=c/2,e=n.assets[CONST_CASH.UNIT.IMAGE],g=b.mode.toUpperCase(),a=new Sprite(c,c),h=new Label,c=CONST_CASH.HAVE,j=CONST_CASH.UNIT.FRAME_LINE,i=0,l=0,k=CONST_CASH.UNIT.AI[g],p,m,q,o,t;a.direction=0;a.image=e;a=z(a,b);a.hplabel=h;h.x=b.x-2;h.y=b.y-14;h.font="9px "+CONST_CASH.FONT;h.color="#FAA";h.backgroundColor="rgba(0,0,0,0.5)";h.width=20;h.update=function(){h.text="\u2020"+a.hp};h.update();w({layer:r[g].UNIT,sprite:h});a.type=
CONST_CASH.TYPE.UNIT;a.attack=function(b,c){b.hp-=c;a.attacked({mine:a,enemy:b});b.hplabel.update();0>=b.hp&&(b.dead({mine:a,enemy:b}),b.kill());return b.hp};a.kill=function(){var b=a.x,c=a.y;new Effect({type:a.type.toUpperCase(),x:b,y:c,frames:CONST_CASH.EFFECT.FRAME.EXPLOSION});Q.play();delete y[g][a.myNo];r[g].UNIT.removeChild(a);r[g].UNIT.removeChild(h);"function"===typeof a.after_death&&setTimeout(function(){a.after_death(a)},1E3*a.reverse);void 0!==a.thumb&&a.thumb.reverse(a)};a.checkDeath=
function(){return 0===a.hp?!0:!1};p=a.frame;a.changeUnit=function(a){p=a.frame};m=function(){return G.getSquere(a)};a.beforePoint=m();q=function(){var b=!1;if(d>=f){var c,e=a.beforePoint;d-=f;if(0<d){switch(a.direction){case 0:a.y+=d;break;case 1:a.x-=d;break;case 2:a.y-=d;break;case 3:a.x+=d}a.y=Math.round(a.y);a.x=Math.round(a.x)}d=0;c=m();if(c.x!==e.x||c.y!==e.y)b=!0}return b};o=function(){return G.getCollision(a)};t=function(){var b=a.direction,c=a.speed,e=CONST_CASH.TYPE,f,g=k.length,i,j;t=function(){if(0===
n.frame%3){d+=c;for(f=0;f<g;f++)if(i=k[f],b===i.direction){a[i.prop]+=c*i.sign;h[i.prop]+=c*i.sign;!0===q()&&(j=o(),!1!==j&&(j.type!==e.CASTLE?a.direction=1===j[i.order[0]]?i.order[0]:1===j[i.order[1]]?i.order[1]:1===j[i.order[2]]?i.order[2]:i.order[3]:C.siege(a,j)));break}}};t()};a.addEventListener(enchant.Event.ENTER_FRAME,t);a.addEventListener(enchant.Event.ENTER_FRAME,function(){if(0===n.frame%5){i++;switch(i){case 4:i=0;l=-1;break;case 3:l=0}l++}a.frame=p+l*j+a.direction});a.stay=function(){r[g].UNIT.removeChild(h);
a.removeEventListener(enchant.Event.ENTER_FRAME,t)};a.myNo=y.no;y[g][y.no]=a;y.no++;g===c.USER&&(d=-d,h.color="#AAF");s.unit(a);return w({layer:r[g].UNIT,sprite:a})};Score=function(b){var c=CONST_CASH.HAVE,f=b.mode,d=b.x,b=b.y,e=new Label,g={},a=function(a){g.total+=a;return g.total};e.font="12px "+CONST_CASH.FONT;e.color="#ccc";e.x=d;e.y=b;g={label:e,total:0,rate:0.5,mode:f,point:I().POINT,add:a,update:function(){}};f===c.USER&&(g.update=function(){e.text="SCORE : "+g.total},g.get=function(){return g.total},
g.add=function(b){a(b);g.update();return g.total},g.rate=1);g.update();return g};Countdown=function(b){var c=new Label,f=CONST_CASH.TIMELIMIT,d=0,e,g=function(){};c.font="12px "+CONST_CASH.FONT;c.color="#ccc";c.x=b.x;c.y=b.y;c.update=function(){c.text="TIME-LIMIT : "+(f-d)};c.init=function(){c.stop();e=setInterval(function(){d++;d>=f&&(g(),c.stop());c.update()},1E3)};c.setAfter=function(a){g=a};c.getDiff=function(){return f-d};c.stop=function(){clearInterval(e)};return c};Effect=function(b){var c=
CONST_CASH.UNIT.CHIP_SIZE,f=b.frames,d=f.start,e=f.end,g=f.rate,f=f.loop,a=b.type.toUpperCase(),h=r.EFFECT[a],j=new Sprite(c,c),i;i=!0===f?function(){0===n.frame%g&&(j.frame>=e?j.frame=d:j.frame++)}:function(){0===n.frame%g&&(j.frame++,j.frame>=e&&j.end())};j.image=n.assets[CONST_CASH.EFFECT.IMAGE];j.x=b.x;j.y=b.y;j.frame=d;j.addEventListener(enchant.Event.ENTER_FRAME,i);j.end=function(){j.removeEventListener(enchant.Event.ENTER_FRAME,i);h.removeChild(j)};return w({layer:h,sprite:j})};var J={aiid:0,
race:"",order:[],init:function(){var b=J,c=CONST_CASH.HAVE.ENEMY,f,d,e,g=x.ENEMY,a=g.length,h=CONST_CASH.UNIT.STATUS,j,i,l;switch(E){case "HUMAN":b.race="UNDEAD";b.order="BONE_DOG,BONE_WARRIER,BONE_ARCHER,SHADE,BONE_SNAKE,GOLEM,SPECTOR,ARACHNE".split(",");break;case "UNDEAD":b.race="HUMAN",b.order="LANCER,WARRIOR,KNIGHT,ARCHER,CLELIC,FIRE_MAGE,FROST_MAGE,WIZARD".split(",")}h=h[b.race];j=b.order;b.aiid=setInterval(function(){i=j.length;0<i&&(e=Math.floor(Math.random()*a),e>=a&&(e=a-1),f=g[e],e=Math.floor(Math.random()*
i),e>=i&&(e=i-1),l=j[e],d=h[l],j.splice(e,1),e={mode:c,direction:2,x:f.unitX,y:f.unitY,after_death:function(a){j.push(a.name)}},e=z(e,d),d=new Unit(e))},6E3)},end:function(){clearInterval(J.aiid)}},C={init:function(){v.add(function(){var b=y.USER,c=y.ENEMY,f,d,e,g;for(e in c)if(!0===c.hasOwnProperty(e))for(g in d=c[e],b)!0===b.hasOwnProperty(g)&&(f=b[g],!0===d.intersect(f)&&(f.x===d.x||f.y===d.y)&&C.unitAndUnit(d,f))},"battle")},score:function(b){var c=CONST_CASH.HAVE,f=b.mode,d=CONST_CASH.TYPE,b=
b.type,e=K,g=CONST_CASH.POINT;b!==d.CASTLE&&f===c.USER||b===d.CASTLE&&f===c.ENEMY?e.add(g[b]):b===d.CASTLE&&f===c.USER&&e.add(-g[b])},unitAndUnit:function(b,c){for(var f=b.hp,d=c.hp,e=f,g=d;0<f&&0<d;)f=b.attack(c,e),d=c.attack(b,g);!0===b.checkDeath()&&(s.death(b),C.score(b));!0===c.checkDeath()&&(s.death(c),C.score(c))},siege:function(b,c){s.siege(c);c.damage(b);b.kill();G.vibrate(3);!0===c.checkBreak()&&(s.castle(c),C.score(c))}},v={functions:{},exefunc:function(){var b,c=v.functions;for(b in c)if(!0===
c.hasOwnProperty(b))c[b]()},add:function(b,c){v.functions[c]=b},remove:function(b){delete v.functions[b]},init:function(){n.addEventListener(enchant.Event.ENTER_FRAME,v.exefunc,!1)},stop:function(){n.removeEventListener(enchant.Event.ENTER_FRAME,v.exefunc,!1)},end:function(){v.functions={};v.stop()}};StatusViwer=function(){var b=new Label,c=new Group,f,d=CONST_CASH.STATUS_VIEWER,e=d.POSITION,g=n.assets[d.IMAGE],d=d.BG_SIZE,a=new Sprite(d[0],d[1]),h=CONST_CASH.UNIT.STATUS,d=CONST_CASH.HAVE.USER,j=
{};c.x=e[0];c.y=e[1];a.image=g;a.frame=0;a.opacity=0;b.font="9px/1.5 "+CONST_CASH.FONT;b.color="#fff";b.text="";b.x=45;b.y=8;f=new Unit({mode:d,x:15,y:15,opacity:0});f.frame=0;f.direction=2;f.stay();c.update=function(a){f.opacity=1;c.update=function(a){b.text=j[a.name];f.changeUnit(a)};c.update(a)};c.init=function(){var b,c,d=h[E];for(b in d)!0===d.hasOwnProperty(b)&&(c=d[b],j[b]="<b>"+c.name+"</b><br />\u2020: "+c.hp+"<br />\u21d2: "+c.speed+"/frame<br />\u00d7: "+c.reverse+"sec");a.opacity=1};c.addChild(a);
c.addChild(b);c.addChild(f);return c};var s={logid:0,data:{time:0,victory:0,unit:{USER:0,ENEMY:0},death:{USER:0,ENEMY:0},siege:{USER:0,ENEMY:0},castle:{USER:0,ENEMY:0}},unit:function(b){s.data.unit[b.mode]++},death:function(b){s.data.death[b.mode]++},siege:function(b){s.data.siege[b.mode]++},castle:function(b){s.data.castle[b.mode]++},send:function(){s.data.time=H.getDiff()},reset:function(){s.data={time:0,unit:{USER:0,ENEMY:0},death:{USER:0,ENEMY:0},siege:{USER:0,ENEMY:0},castle:{USER:0,ENEMY:0}}},
init:function(){s.reset()},end:function(){s.send();clearInterval(s.logid)}};Result=function(b){var c=new Scene,f=new Label,d=new Label,e=CONST_CASH.HAVE,g=K.get(),a=CONST_CASH.POINT,h;h="SCORE: "+g+"<br>";switch(b){case e.ENEMY:b="WIN";s.data.victory=1;e=H.getDiff()*a.TIME;h+="&nbsp;WIN: "+a.WIN+"<br>&nbsp;CLEAR TIME BONUS: "+e;g+=a.WIN+e;break;case e.USER:b="LOSE";s.data.victory=-1;h+="&nbsp;LOSE: "+a.LOSE;g+=a.LOSE;break;default:b="DRAW",h+="&nbsp;DRAW: 0"}a=CONST_CASH.FONT;f.font="20px/1.5 "+a;
f.color="#fff";f.text="RESULT";f.x=100;f.y=100;d.font="12px/1.5 "+a;d.color="#fff";d.text=h+("<br><br><b>TOTAL: "+g+"</b>");d.x=100;d.y=150;c.addChild(f);c.addChild(d);c.backgroundColor="rgba(0,0,0,0.3)";n.pushScene(c);n.end(g,b+":"+g)};return PUBLIC}(window);AW.init({map:"\u25a0\u00d7\u25a0\u00d7\u25a0\u00d7\u25a0\u00d7,\u251c\u2500\u2524\u00d7\u2502\u00d7\u2502\u00d7,\u2502\u00d7\u2502\u00d7\u251c\u2500\u2524\u00d7,\u2502\u00d7\u2514\u2510\u2502\u00d7\u2502\u00d7,\u2514\u2510\u00d7\u251c\u2524\u00d7\u2514\u2510,\u00d7\u2502\u00d7\u2502\u2514\u2510\u00d7\u2502,\u00d7\u251c\u2500\u2524\u00d7\u2502\u00d7\u2502,\u00d7\u2502\u00d7\u2502\u00d7\u251c\u2500\u2524,\u00d7\u25a1\u00d7\u25a1\u00d7\u25a1\u00d7\u25a1".split(",")});
